apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testchatbotrhoai 
  janus-idp.io/tekton: testchatbotrhoai
  backstage.io/kubernetes-id: testchatbotrhoai
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testchatbotrhoai
resources: 
- application-dev.yaml