---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: testchatbotrhoai
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testchatbotrhoai 
  name: testchatbotrhoai
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi