apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: testchatbotrhoai
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testchatbotrhoai 
  name: testchatbotrhoai
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: testchatbotrhoai 
    weight: 100 
  wildcardPolicy: None
