apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testchatbotrhoai
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testchatbotrhoai 
  name: testchatbotrhoai
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: testchatbotrhoai 
